export const Careers = [
  {
    start: "2000년 10월",
    end: "2006년 02월",
    duration: "5년 4개월",
    company: "(주)트랜스넷",
    position: "대리",
    description: "소프트웨어 개발",
  },
  {
    start: "2006년 02월",
    end: "2011년 07월",
    duration: "5년 5개월",
    company: "SK커뮤니케이션즈",
    position: "차장",
    description: "소프트웨어 개발",
    image: "/careers/SK.jpg",
  },
  {
    start: "2011년 08월",
    end: "2012년 12월",
    duration: "1년 5개월",
    company: "네오위즈게임즈",
    position: "팀장",
    description: "소프트웨어 개발",
    image: "/careers/neowiz.png",
  },
  {
    start: "2013년 02월",
    end: "2016년 06월",
    duration: "3년 5개월",
    company: "(주)아크로메이트",
    position: "팀장",
    description: "소프트웨어 개발",
  },
  {
    start: "2016년 07월",
    end: "2018년 07월",
    duration: "2년",
    company: "휴스케일(개인사업자)",
    position: "사장",
    description: "",
    image: "/shared/logo.png",
  },
  {
    start: "2018년 07월",
    end: "현재",
    company: "(주)휴스케일",
    position: "대표이사",
    description: "",
    image: "/shared/logo.png",
  },
  {
    start: "2022년 09월",
    end: "2023년 03월",
    duration: "6개월",
    company: "(주)한그루",
    position: "CTO",
    description: "(주)휴스케일 대표이사 및 겸직",
    image: "/careers/hangloo.png",
  },
  {
    start: "2024년 03월",
    end: "현재",
    company: "(주)엠원소프트",
    position: "사외이사(등기)",
    description: "(주)휴스케일 대표이사 및 겸직",
  },
];
