export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "휴스케일",
  description: "Generated by create next app",
};

export const siteRoutes = [
  { label: "휴스케일", route: "main" },
  { label: "대표이력", route: "career" },
  { label: "포트폴리오", route: "portfolio" },
  { label: "파트너사", route: "partners" },
  { label: "구성원", route: "members" },
  { label: "문의", route: "contact" },
];
